# Generated by Django 3.1 on 2020-08-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name_plural': 'allergies'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'food'},
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
