# Generated by Django 3.1 on 2020-08-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200824_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='restaurant',
        ),
    ]
