# Generated by Django 3.1 on 2020-08-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address3',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Address line 3'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Address line 2'),
        ),
    ]
